# ============================================================
# Agent-Nexus 核心配置
# Data ID: agent-nexus.yaml | Group: DEEPKNOW_GROUP
# ============================================================

server:
  port: 8003

spring:
  datasource:
    # 引用 common.yaml 变量拼接完整 URL
    url: jdbc:mysql://${database.host}:${database.port}/agent_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: deepknow_agent_nexus
    password: Aa1231231212123
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      validation-query: SELECT 1

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      username: deepknow_agent_nexus
      password: Aa1231231212123
      database: 2
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.deepknow.nexus.**.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: none

# Dubbo 配置 (引用 common.yaml 的 Nacos 地址)
dubbo:
  protocol:
    name: dubbo
    port: 20883
  registry:
    address: nacos://${nacos.server-addr}
    username: ${nacos.username}
    password: ${nacos.password}
    group: ${nacos.group}

# DashScope API 配置
dashscope:
  api:
    key: sk-3bf5c683d8314b3cab4be8e823ec558f

# Codex-Agent gRPC 客户端配置
codex:
  agent:
    enabled: true
    endpoint: http://localhost:9000
    timeout: 30000

# MCP Tool 配置
mcp:
  servers:
    WebSearch:
      type: sse
      description: "基于通义实验室 Text-Embedding，GTE-reRank，Query 改写，搜索判定等多种检索模型及语义理解，串接专业搜索工程框架及各类型实时信息检索工具，提供实时互联网全栈信息检索，提升 LLM 回答准确性及时效性。"
      isActive: true
      name: "阿里云百炼_联网搜索"
      baseUrl: "https://dashscope.aliyuncs.com/api/v1/mcps/WebSearch/sse"
      headers:
        Authorization: "Bearer ${dashscope.api.key}"
      timeoutSeconds: 30

# 日志配置
logging:
  level:
    com.deepknow.nexus: INFO
    org.apache.dubbo: INFO

# SLS 日志配置 (引用 common.yaml 的基础配置)
sls:
  project: deepknow
  logstore: agent-nexus
